### ISSUE TITLE
Use multiple address spaces in vnet

### ISSUE THREAD

**Issue by t-young31** [UCLH-Foundry/FlowEHR#104]
Due to the [inability to rearrange subnets](https://github.com/UCLH-Foundry/FlowEHR/actions/runs/4242793652/jobs/7374739423#step:5:913) while resources are deployed the vnet should be split into multiple address spaces. https://github.com/UCLH-Foundry/FlowEHR/pull/79 adds a /26 address space for webapps which may not be enough

aside: databricks cannot operate in a /27 subnet

**Comment by jjgriff93** [comment]
@t-young31 is this done now?

**Comment by t-young31** [comment]
Given that we're deploying into a /22 range I don't see this being an issue – 🤞🏼 anyway
