### ISSUE TITLE
Enable promotion of app image from staging to production slots (slot swapping) in same environment

### ISSUE THREAD

**Issue by jjgriff93** [UCLH-Foundry/FlowEHR#131]
As per design doc, we should enable an app config setting that defines multiple slots for an app to differentiate between app environments within the same FlowEHR environment (i.e. staging and production).

This should add an additional GitHub environment secret for the web app publishing profile so the developer's GitHub action can do a slot swap.

**Comment by t-young31** [comment]
Started looking at this and wondering if it is possible to do a slot swap with only a publish profile. Seems like auto-swap isn;t what we want. Relevant issue: https://github.com/Azure/webapps-deploy/issues/113
