### ISSUE TITLE
Configure IP Address ranges

### ISSUE THREAD

**Issue by damoodamoo** [UCLH-Foundry/FlowEHR#193]
- [x] Make the IP address ranges configurable, so the environment / config can drive it
- [ ] Set up the ranges per environment such(https://github.com/UCLH-Foundry/Book-of-FlowEHR/blob/the-walking-skeleton/milestones/walking-skeleton/scaffolding/address-spaces.md)

| Component | Environment | CIDR Range | Start -> End | No. Addresses |
|--|--|--|--|--|
| **FlowEHR** | _all_ | `10.64.0.0/16` | `10.64.0.1` -> `10.64.255.254` | 65,534 |
| | Infra-Test | `10.64.0.0/22` | `10.64.0.1` -> `10.64.3.254` | 1,022 |
| | App Dev | `10.64.4.0/22` | `10.64.4.1` -> `10.64.7.254` | 1,022 |
| | ML Dev | `10.64.8.0/22` | `10.64.8.1` -> `10.64.11.254` | 1,022 |
| | Prod | `10.64.12.0/22` | `10.64.12.1` -> `10.64.15.254` | 1,022 |
| **FlowEHR PR** | PR |  | `10.65.0.0` -> `10.69.255.254` | ~327,620 (used for randomising FlowEHR PR deployment address spaces) |

**Comment by t-young31** [comment]
@damoodamoo even using a /24 for PR builds there's not much space in 10.65 -> 10.69 (~2 % chance of clash?). any way we could get something wider for PR? (sorry for not picking this up on your doc)

**Comment by damoodamoo** [comment]
@t-young31 yes I think we can rejig them, and we need address spaces for the build vnets too, I can update the IP doc.

**Comment by anastasiakuzn** [comment]
@damoodamoo , this item is related to this PR, is that righg: https://github.com/UCLH-Foundry/Book-of-FlowEHR/pull/184 ? Therefore, when the PR is merged, this can be closed?
