### ISSUE TITLE
Initial automation for scheduling an ADF Databricks job

### ISSUE THREAD

**Issue by tanya-borisova** [UCLH-Foundry/FlowEHR#21]
As a Data Engineer,
I want to have a script for scheduling an ADF Databricks job,
So that I'm one step closer into having automated deployments of the data pipeline

Acceptance criteria:

- [x] Script that uploads the [packaged Python wheel](https://github.com/UCLH-Foundry/FlowEHR/issues/20) to DFBS
- [x] Script for scheduling an ADF job on Databricks using the uploaded Python wheel
- [x] Any terraform configuration required for this (e.g. any outputs from Databricks infra)

**Comment by tanya-borisova** [comment]
Dependent on https://github.com/UCLH-Foundry/FlowEHR/pull/31 and https://github.com/UCLH-Foundry/FlowEHR/pull/34

**Comment by jjgriff93** [comment]
Revised plan:

1. Add ADF pipeline json to `./transform/pipelines`
2. Add Databricks job definition json to `./transform/jobs` 
3. Rename `transform/pipeline` to `transform/features`
4. Add Terraform to `./infrastructure/transform/pipeline.tf` that deploys ADF pipeline(s) and Databricks job(s)
5. Root makefile deploy and deploy-transform should call `./transform make build` as a dependency

**Comment by jjgriff93** [comment]
Test whether whl files can be uploaded to DBFS via Terraform https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/dbfs_file

**Comment by jedheaj314** [comment]
("relatively small") Files can be uploaded to DBFS via Terraform.
We have decided to use Terraform to upload files to DBFS.
