### ISSUE TITLE
Data Lakehouse

### ISSUE THREAD

**Issue by marrobi** [UCLH-Foundry/FlowEHR#226]
The data lakehouse will be our repository for both raw and transformed data. A sustainable and
flexible storage strategy which follows data architecture best practice is required as we will need to support other data modalities beyond tabular EHR data in the near future. The lakehouse needs clear and maintainable RBAC, close integration with the metadata catalogue and a user-friendly querying interface.

- [ ] #160 (ADLS)
- [ ] #313
- [ ] #314

**Comment by jjgriff93** [comment]
Suggest we have DICOM and FHIR as their own feature requests and close this
