### ISSUE TITLE
CIS/prod requirements - should logs be publicly accessible through Azure portal or private? And how to access if so?

### ISSUE THREAD

**Issue by jjgriff93** [UCLH-Foundry/FlowEHR#234]
We need to define the requirements for viewing platform logs (i.e. general logs from azure services, serve app logs) and how we intend to view them.

If we are required to disable public portal access to Log Analytics and Application insights data, how will people operating FlowEHR view logs and troubleshoot?

**Comment by anastasiakuzn** [comment]
@RichardClarke-dm, apologies, I forgot to bring it up at the standup. Any thoughts / update on this?

**Comment by RichardClarke-dm** [comment]
Thanks @anastasiakuzn. Are there any risks with current settings in keeping public access. I believe this may need to be the approach until we have the concept of an admin VM or dashboard that brings this together at Landing Zone level. @dram1964 would you second this approach? Do we need to start looking at the SOP related to management/review of logs?

**Comment by damoodamoo** [comment]
Yes - this is related to the VNET isolation of logs. They will still be RBAC controlled - but this issue might want to remain open to prompt the future work of VNET isolating the logs, when the general Azure Administration story has been fleshed out. Not a CIS issue, don't think it should prevent us deploying into prod in the immediate term.
