### ISSUE TITLE
Infra-test failed after merge of branch done for #183 - (Group pemissions)

### ISSUE THREAD

**Issue by jedheaj314** [UCLH-Foundry/FlowEHR#255]
make all was triggered as automation step after merge of branch created for 183

Here is the result

https://github.com/UCLH-Foundry/FlowEHR/actions/runs/4720852145/jobs/8373410300#step:9:1478

To reproduce:

Triggger the infra-test action on the workflows of FlowEHR
or
run make all on build environment

**Comment by jjgriff93** [comment]
Fixed by manually updating state with the new principal id created in core
