### ISSUE TITLE
Add Jumpbox VM / mechanism for CICD and local deployment to VNet

### ISSUE THREAD

**Issue by jjgriff93** [UCLH-Foundry/FlowEHR#27]
We need a [self-hosted runner](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) to be deployed into the core vnet as part of a `ci-bootstrap` workflow, so that we can deploy both infrastructure and data plane resources within a virtual network.

- [ ] Terraform code to deploy VM/Container instance with runner app installed
- [ ] Networking rules to allow [communication between runner and GitHub](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#communication-between-self-hosted-runners-and-github)
- [ ] make command/script to be called to initiate bootstrapping

**Comment by t-young31** [comment]
I'm slightly loathed to make the build agent a GH runner as that removes the possibility of running a local `make deploy`. Possibilities: log streaming, local VPN client, ssh access(?)

**Comment by t-young31** [comment]
based on a discussion with @marrobi / @damoodamoo the plan is to try a VM.

local dev flow: open devcontainer -> make build-agent in core vnet -> open devcontainer in vm -> make deploy
CI: same(?) execute remote ssh command

**Comment by jjgriff93** [comment]
Current method to explore: invoking Dev Container remotely on a VM running within the Virtual Network. Advantages are that set-up time should be minimal compared to a VPN to allow for transient environments and means we can use the same approach locally and with GitHub Actions. Things to test:

- [ ] copying docker images over SSH (and that the inline metadata is included)
- [ ] controlling the location of the local feature content and copying that over SSH
- [ ] if the first two steps are successful then test building, copying and then running the devcontainer build command to check that it re-uses cached layers
