### ISSUE TITLE
Github Actions CI CD deployment failing

### ISSUE THREAD

**Issue by slawpast** [UCLH-Foundry/FlowEHR#280]
**Describe the bug**
I tried to follow the guide for CI (Github Actions) and got deployment errors.

1. Create repository from  UCLH-Foundry/FlowEHR.
2. Clone new repository into VS Code.
3. Open in a dev container
4. Remove line 5 from config.infra-test.yaml file _(private_dns_zones_rg)_
5. Update config.yaml file (flowehr_id - updated flowehr_id)
6. Run az login.
7. Run `make auth`
At the prompt:
- specify resource group name
- specify a storage account

<i>First error at this point, storage account does not exist.</i>

8. Create a storage account and a container.
9. run again `make auth` and specify resource group name and a storage account name from point 6.

<i>At this point, the guide says that  CI_GITHUB_RUNNER_LABEL should be outputted - but it wasn't)</i>

10. Create a GitHub PAT (access token)
11. Add new environment `infra-test` and following secrets and variables

VARIABLES:
CI_RESOURCE_GROUP: name of the resource created at point 8.
CI_STORAGE_ACCOUNT: name of the resource created at point 8.
CI_CONTAINER_REGISTRY: a string (cgbuildagentflowspdev)
CI_PEERING_VNET: a string (vnflowspdev)
CI_GITHUB_RUNNER_LABEL: a string (CI_RUNNER)
SECRETS:
ARM_CLIENT_ID: an output from point 9
ARM_TENANT_ID: an output from point 9
ARM_SUBSCRIPTION_ID: an output from point 9
ARM_CLIENT_SECRET: an output from point 9
FLOWEHR_REPOSITORIES_GH_TOKEN: an output from point 10

13. Stage, commit and push changes.

**Error**
<i>Error when evaluating 'runs-on' for job 'make'.  slawpast/flower-full/.github/workflows/devcontainer_make_command.yml @ 82a6948559e7885c25b8344d41bdcacd89af3adc (Line: 62, Col: 28): </i>

14. Update `devcontainer_make_command.yml` file: change line 62: `runs-on: ubuntu-latest`
15. Stage, commit and push changes.

**Error**
_WARNING: The resource with name 'cgbuildagentflowspdev' and type 'Microsoft.ContainerRegistry/registries' could not be found in subscription 'Visual Studio Enterprise Subscription – MPN (***)'.
Using 'cgbuildagentflowspdev.azurecr.io' as the default registry login server.
ERROR: Could not connect to the registry login server 'cgbuildagentflowspdev.azurecr.io'. Please verify that the registry exists and the URL 'https://cgbuildagentflowspdev.azurecr.io/v2/' is reachable from your environment.'_

16. Create container registry (cgbuildagentflowspdev) in CI_RESOURCE_GROUP resource group 
17. Run action `Deploy Infra-Test `

**Error on Make command**
_Error: Failed to get existing workspaces: containers.Client#ListBlobs: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ContainerNotFound" Message="The specified container does not exist.\nRequestId:07b31d14-a01e-0033-1282-774c57000000\nTime:2023-04-25T14:27:17.6067623Z"_

Hopefully that does make sense. Any further guide on the ci/cd deployment will be much appreciated

**Comment by marrobi** [comment]
The deployment was refactored recently. I will check with the team at UCLH, but believe this https://github.com/UCLH-Foundry/Azure-Bootstrap is a prerequisite when doing CI/CD.

**Comment by jjgriff93** [comment]
Hey @slawpast - looks like you're missing step 4:

```
4. Deploy a bootstrap environment

    For CI deployments, due to certain resources being deployed within a Virtual Network with public access disabled, we need to use private build agents (also called self-hosted GitHub runners) to run our CI pipelines. We also need somewhere to store the associated container images and Terraform state within a vnet.

    You can use [the Azure Bootstrap template](https://github.com/UCLH-Foundry/Azure-Bootstrap) to deploy all these resources, or alternatively, you can reference pre-existing resources in the next step.
```

There is a typo on the readme saying `CI_GITHUB_RUNNER_LABEL` should be populated from the previous step (which is running `make auth`) which is wrong, so just fixed that - thanks for spotting. It should be populated from the outputs of running the `Azure-Bootstrap` deployment

**Comment by slawpast** [comment]
Thank you for your help. I will update CI_GITHUB_RUNNER_LABEL, use the bootstrap and see if it works.
