### ISSUE TITLE
Running make-clean / tf-reinit doesn't always work to refresh the state files

### ISSUE THREAD

**Issue by akolensky** [UCLH-Foundry/FlowEHR#288]
**Describe the bug**
We are a team of 3 developers deploying flowerehr on a single tenant. 
Someitmes the state files have changed, and requests us to import the resources individually. 

We try to run make-reinit command to update the lock files and backend state changes but after that runs successfully, it still requests to import some of the modules.

Are there better ways to manage the state file? something like remote state ?

**Comment by jjgriff93** [comment]
State files are persisted remotely when running via CI. For local scenarios, it sounds like a remote resource is being modified outside of TF's state and that's when TF would prompt to manually import, so try to avoid this and only make changes via FlowEHR's make commands.

Closing as this sounds like an issue unrelated to codebase, but feel free to re-open if any questions or new errors.
