### ISSUE TITLE
Integrate FlowEHR and a repo for data pipeline code

### ISSUE THREAD

**Issue by tanya-borisova** [UCLH-Foundry/FlowEHR#32]
As a Data Engineer,
I need a repo where my pipeline code lives and a way to deploy it together with the rest of FlowEHR
So that I can iterate on my pipeline code, and we can make sure the repo is private as required.

Acceptance Criteria:
- [x] #35
- Repo is set up to build Python packages (wheels) and run unit tests for pipeline code
- FlowEHR repo can use this wheel built from pipeline code repo 
- [ ] #81

Implementation detail:

On the last part, I see several ways to do it: 
1. Build the Python wheel as part of a CI/CD process for the data pipeline repo, then consume it in FlowEHR during deployment of the job 
2. Check out pipeline repo into the devcontainer similar to how TRE does it (or the other way around, check out FlowEHR into the data pipeline code repo) and then run the build and deploy process from there

**Comment by jjgriff93** [comment]
I'd be in favour of the second approach so we can minimise repeating any CICD code / keeping potentially useful and generic deployment code in a private repo instead of the public one

**Comment by tanya-borisova** [comment]
@jjgriff93  but in the second approach then, should we check out pipeline code into FlowEHR, or should we check out FlowEHR into the pipeline code repo? The latter is how the deployment repo on TRE works
