### ISSUE TITLE
CI/CD running data pipeline in FlowEHR

### ISSUE THREAD

**Issue by tanya-borisova** [UCLH-Foundry/FlowEHR#54]
As a Data Engineer
I want to make sure that FlowEHR runs integration tests on data pipeline
So that I can be confident that my pipeline works with the rest of FlowEHR

Acceptance criteria: 
- Github Action workflow step that checks that checks that the data pipeline has ran successfully

Notes:
- The idea is that he data pipeline will have data quality checks that constitute part of this integration test
- Unit tests for the data pipeline code will run in its own repo 

- [x] #137

**Comment by damoodamoo** [comment]
Possibly for the future but quality checks are interesting - we might need the ability to switch them on/off - if we're running against synth data in a PR / infra-test then i'd _guess_ all the data quality checks (like "a heart rate should be 20 - 120") would likely fail

**Comment by tanya-borisova** [comment]
Blocked yet another time, this time by not having data source secrets in Databricks secret scope:

![image](https://user-images.githubusercontent.com/52954123/224757728-59f2b83b-45fd-49f2-9e9c-e5f4e85679fe.png)

**Comment by tanya-borisova** [comment]
Blocked on not having an environment setup for UCLH-FlowEHR in which to run these tests
