### ISSUE TITLE
AML Experimentation

### ISSUE THREAD

**Issue by anastasiakuzn** [UCLH-Foundry/FlowEHR#60]
Description

In order to onboard UCLH and MS data science teams onto the Walking Skeleton project and its MLOps workstream, the following onboarding sessions have been identified:

- [x] TRE Onboarding Session
- [x] AML Upskilling Session by @ayabel 
- [x] Create a simple model in AML within TRE using a public dataset 
- [ ] Document the recommendations on interaction of Data Scientists with AML and TRE
- [ ] ~~Create a repo in UCLH Foundry Org for MLOps Experimentation~~

Acceptance Criteria 

- Aya, Tom F, Ahmed, Tom K, Zella to be onboarded onto TRE and how to operate within TRE
- Aya to bring people up to speed with AML
-  Training of a simple model on AML with performance metrics that a data-scientist can then iterate on

**Comment by ahmed-alhindawi** [comment]
Just to update the PR; we now have data in the TRE (open source publically available data), that we can set-up as a data source inside AML. I have modified Aya's code to run a simple logistic regression model based on that code with the appropriate MLFlow hooks.

We're able to successfully create the job and pipeline, but the AML instance requires a docker image to run the dependency installs on which is currently blocked by firewall/configuration issue of the private AML instance.

**Comment by ahmed-alhindawi** [comment]
As per the stand-up on 28/02/23: The acceptance criteria for the AML experimentation story is for the training of a simple model on AML with some performance metrics that a data-scientist can then iterate on.

**Comment by ahmed-alhindawi** [comment]
![image](https://user-images.githubusercontent.com/6945849/222282065-5a820b12-3a5a-465b-a5fa-f73483df5aeb.png)

I officially declare this story...unblocked
