### ISSUE TITLE
Dev Container Can't Find Spark 3.3.1

### ISSUE THREAD

**Issue by martinpeck** [UCLH-Foundry/FlowEHR#87]
When building the dev container we are seeing 404 errors during the Docker build step.
This is because version 3.3.1 of the spark download is no longer present on Apache's downloads site.
As of 15th Feb a new version (3.3.2) has bumped 3.3.1 to the archive location.

Given that 3.3.1 is the supported version for Databricks on Azure, the fix is to use the archives URL instead. i.e.

Current:
`https://downloads.apache.org/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop3.tgz`

Suggested change:
`https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop3.tgz`

In fact, the archives location is better generally as it contains the latest version and all previous versions, so breaks like this won't be as likely.

**Comment by t-young31** [comment]
fixed in https://github.com/UCLH-Foundry/FlowEHR/pull/80
