### ISSUE TITLE
Define Base Operating Systems for Custom VMs

### ISSUE THREAD

**Issue by martinpeck** [UCLH-Foundry/FlowEHR#89]
We need to define which operating systems to base our custom VMs up.

Assumption is the following:

1. Linux VMs will be based upon Ubuntu Server 22.04 LTS
2. Windows VMs will be based upon Windows 11 Pro (win11-21h2-pro)

**Comment by martinpeck** [comment]
@dram1964 @nels If the above assumptions are OK with you, please say so here and then we can close this issue.
cc @anastasiakuzn

**Comment by dram1964** [comment]
Yes - 22.04 LTS for Ubuntu and Windows 11 Pro for Windows

**Comment by martinpeck** [comment]
Thanks. Let's close this with the above OS decisions.
