### ISSUE TITLE
Manually Deploy Core Infra to Support Custom VMs

### ISSUE THREAD

**Issue by martinpeck** [UCLH-Foundry/FlowEHR#91]
The `make vm-deploy-code` needs to be run in the following environments so that the core infrastructure to support custom VMs is in place:

- [x] deploy custom vm core infra into the dev environment (dev subscription)
- [x] deploy custom vm core infra into the prod environment (prod subscription)

in both cases, the environment files need to be committed into `/scripts/environments` as .env files

**Comment by dram1964** [comment]
Deployed dev and prod infra to Landing Zone and also deployed dev infra to UCLH-DIF for dev testing from TRE
