### ISSUE TITLE
Manually Deploy Custom Role into Subscription

### ISSUE THREAD

**Issue by martinpeck** [UCLH-Foundry/FlowEHR#92]
We need to deploy the custom aad role required for Azure Image Builder to access other resources.

i.e. `make vm-create-role` needs running in each subscription.

Task is therefore to:

- [x] deploy custom role to the dev subscription
- [x] deploy custom role to the prod subscription

**Comment by dram1964** [comment]
roles deployed to dev and prod subscriptions on the Landing Zone subscription and to UCLH-DIF tenant that we'll be using for our DEV environment
