### ISSUE TITLE
Define specific customisations for Innovator Linux VM

### ISSUE THREAD

**Issue by martinpeck** [UCLH-Foundry/FlowEHR#96]
Using the following document as a base line...

https://github.com/UCLH-Foundry/Book-of-FlowEHR/blob/the-walking-skeleton/milestones/walking-skeleton/innovator-vm/innovator-vm-design.md

... the following items will be installed into an Ubuntu Server 22.04 LTS:

- [x] VS Code (latest build)
   - [x] ms-python.vscode-pylance
   - [x] ms-toolsai.vscode-ai-remote
   - [x] ms-toolsai.vscode-ai 
- [x] Python3 (3.10)
- [x] Anaconda (latest)
- [x] R (latest)
    - [x] RStudio (latest)
    - [ ] RMarkdown
    - [ ] LaTeX in RStudio
- [x] DBeaver (latest)
- [x] Azure Storage Explorer
- [x] AZCopy
- [x] Azure CLI
- [x] PyCharm CE
- [x] Google Chrome
- [x] Docker CE

**Comment by ahmed-alhindawi** [comment]
For @tdgfrost's sanity - could I kindly ask to add in PyCharm Community Edition also, please? Other than that - that list is exhaustive.

**Comment by martinpeck** [comment]
I'm going to consider this "done" for now.
It may not be perfect, but v1 of the list is now defined.
